# Generated by Django 3.2.25 on 2025-10-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_subactivity_subactivity_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Fiscal Year')),
                ('output_indicator', models.CharField(blank=True, max_length=255)),
                ('target_indicator', models.CharField(blank=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
                ('subprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subprogram')),
            ],
        ),
    ]
