# Generated by Django 3.2.25 on 2025-10-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_subactivity_subactivity_number'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.activity'),
        ),
    ]
