# Generated by Django 3.2.25 on 2025-10-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.IntegerField(choices=[(1, 'Executives'), (2, 'Division'), (3, 'Section'), (4, 'Unit'), (5, 'Provincial')], max_length=2)),
                ('office_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['office_type'],
            },
        ),
    ]
