# Generated by Django 3.2.25 on 2025-10-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndUsers',
            new_name='EndUser',
        ),
    ]
