# Generated by Django 3.2.25 on 2025-10-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0002_rename_endusers_enduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='office_name',
            field=models.CharField(max_length=255, verbose_name='Office Name'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='office_type',
            field=models.IntegerField(choices=[(1, 'Executives'), (2, 'Division'), (3, 'Section'), (4, 'Unit'), (5, 'Provincial')], max_length=2, verbose_name='Office Type'),
        ),
    ]
