# Generated by Django 3.2.25 on 2025-10-13 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.CharField(max_length=5, unique=True)),
                ('program', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['program_number'],
            },
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprogram_number', models.CharField(max_length=5, unique=True)),
                ('subprogram', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprograms', to='core.program')),
            ],
        ),
    ]
