# Generated by Django 3.2.25 on 2025-10-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='subprogram',
            field=models.CharField(max_length=255, verbose_name='Sub-Program Name'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='subprogram_number',
            field=models.CharField(max_length=5, verbose_name='Sub-Program Number'),
        ),
        migrations.AddConstraint(
            model_name='subprogram',
            constraint=models.UniqueConstraint(fields=('program', 'subprogram_number'), name='unique_subprogram_per_program'),
        ),
    ]
