# Generated by Django 3.2.25 on 2025-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251013_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='subprogram',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='subprogram_number',
            field=models.CharField(max_length=5),
        ),
    ]
