# Generated by Django 3.2.25 on 2025-10-13 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251013_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subprogram',
            options={'ordering': ['program__program_number', 'subprogram_number']},
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_number', models.CharField(max_length=5)),
                ('activity', models.CharField(max_length=255)),
                ('subprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.subprogram')),
            ],
        ),
    ]
