# Generated by Django 3.2.25 on 2025-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251013_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['activity_number'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('subprogram', 'activity_number'), name='unique_activity_per_subprogram'),
        ),
    ]
