# Generated by Django 3.2.25 on 2025-10-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20251013_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_number',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_number',
            field=models.IntegerField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='subprogram_number',
            field=models.IntegerField(max_length=5),
        ),
    ]
