# Generated by Django 3.2.25 on 2025-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251014_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=255, verbose_name='Activity Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.CharField(max_length=255, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='subprogram',
            field=models.CharField(max_length=255, verbose_name='Sub-Program Name'),
        ),
    ]
