# Generated by Django 3.2.25 on 2025-10-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20251014_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='subprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.subprogram', verbose_name='Sub-Program Name'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprograms', to='core.program', verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='subprogram_number',
            field=models.IntegerField(max_length=5, verbose_name='Sub-Program Number'),
        ),
        migrations.CreateModel(
            name='SubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subactivity_number', models.IntegerField()),
                ('subactivity', models.CharField(max_length=255, verbose_name='Sub-Activity Name')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subactivities', to='core.activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name_plural': 'Sub-Activities',
                'ordering': ['activity__subprogram__program__program_number', 'activity__subprogram__subprogram_number', 'activity__activity_number', 'subactivity_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='subactivity',
            constraint=models.UniqueConstraint(fields=('activity', 'subactivity_number'), name='unique_subactivity_per_activity'),
        ),
    ]
