# Generated by Django 3.2.25 on 2025-10-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251014_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactivity',
            name='subactivity_number',
            field=models.CharField(max_length=5, verbose_name='Sub-Activity Number'),
        ),
    ]
